steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - '${_IMAGE}'
  - '--build-arg'
  - 'VITE_API_BASE_URL=https://kantin-backend-104030083079.asia-southeast2.run.app/api/v1'
  - '.'
images: ['${_IMAGE}']